<a href="https://colab.research.google.com/github/parthibnandi555/Machine_learning/blob/main/LSTM%2CRNN%2CGRU_project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/qoute_dataset.csv")

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
df['quote'][2]

'“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”'

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes = df['quote']

In [ ]:
quotes = quotes.str.lower()

In [ ]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size =8978
tok= Tokenizer(num_words=vocab_size)
tok.fit_on_texts(quotes)

In [ ]:
word_index = tok.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:

Sequence = tok.texts_to_sequences(quotes)

In [ ]:
for i in range(3):
  print(quotes[i])
  print(Sequence[i])
quotes[0]

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
“it is our choices harry that show what we truly are far more than our abilities”
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [ ]:
Sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [ ]:
 X =[]
 y =[]
 for seq in Sequence :
  for i in range(1,len(seq)):
    input_seq=seq[:i]
    output_seq=seq[i]
    X.append(seq[:i])
    y.append(seq[i])

In [ ]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [ ]:
len(X)
len(y)

85270

# we use padding to make it in same sequence..

#1st we need to find max length

In [ ]:
max_len = max(len(x)for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X,maxlen=max_len,padding='pre')

In [ ]:
X_padded.shape

(85270, 745)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot =to_categorical(y, num_classes = vocab_size)

In [ ]:
y_one_hot.shape

(85270, 8978)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import  SimpleRNN,Embedding,LSTM,Dense

In [ ]:
Embedding_dim =50
rnn_units =128

In [ ]:
rnn_model =Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=Embedding_dim,
              input_length=max_len)

)
rnn_model.add(SimpleRNN(units=rnn_units,activation='tanh',return_sequences=True))
rnn_model.add(SimpleRNN(units=rnn_units,activation='tanh'))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(
    optimizer ='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
rnn_model_1 =Sequential()

rnn_model_1.add(
    Embedding(input_dim=vocab_size,output_dim=Embedding_dim,
              input_length=max_len)
)

rnn_model_1.add(LSTM(units=rnn_units,activation='tanh',return_sequences=True))
rnn_model_1.add(LSTM(units=rnn_units,activation='tanh'))
rnn_model_1.add(Dense(units=vocab_size,activation='softmax'))

In [ ]:
rnn_model_1.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs =100
batch_size =128

rnn_model_1.compile(
    optimizer ='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
histlory_rnn_1 =rnn_model_1.fit(X_padded,y_one_hot,epochs=epochs,batch_size=batch_size,
                            validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 70s 103ms/step - accuracy: 0.0375 - loss: 6.7811 - val_accuracy: 0.0435 - val_loss: 6.6775
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.0529 - loss: 6.3615 - val_accuracy: 0.0591 - val_loss: 6.6005
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.0678 - loss: 6.1335 - val_accuracy: 0.0720 - val_loss: 6.5139
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.0837 - loss: 5.9536 - val_accuracy: 0.0864 - val_loss: 6.4941
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.0961 - loss: 5.7987 - val_accuracy: 0.0912 - val_loss: 6.4945
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1045 - loss: 5.6626 - val_accuracy: 0.0953 - val_loss: 6.4907
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1102 - loss: 5.5395 - val_accuracy: 0.0983 - val_loss: 6.5128
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1166 - loss: 5.4217 - val_accuracy: 0.0997 - val_loss: 6.5212
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1227 - loss: 5.3088 - val_accuracy: 0.1020 - val_loss: 6.5382
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1270 - loss: 5.2034 - val_accuracy: 0.1014 - val_loss: 6.5775
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1310 - loss: 5.1016 - val_accuracy: 0.1034 - val_loss: 6.6115
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1351 - loss: 5.0022 - val_accuracy: 0.1044 - val_loss: 6.6718
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1391 - loss: 4.9054 - val_accuracy: 0.1058 - val_loss: 6.7237
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 110ms/step - accuracy: 0.1428 - loss: 4.8287 - val_accuracy: 0.1013 - val_loss: 6.7243
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1471 - loss: 4.7366 - val_accuracy: 0.1052 - val_loss: 6.7870
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1525 - loss: 4.6442 - val_accuracy: 0.1053 - val_loss: 6.8801
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1585 - loss: 4.5529 - val_accuracy: 0.1084 - val_loss: 6.9549
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1650 - loss: 4.4682 - val_accuracy: 0.1084 - val_loss: 7.0376
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1711 - loss: 4.3948 - val_accuracy: 0.1048 - val_loss: 7.1203
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.1795 - loss: 4.3143 - val_accuracy: 0.1047 - val_loss: 7.1838
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 85s 111ms/step - accuracy: 0.1881 - loss: 4.2389 - val_accuracy: 0.1045 - val_loss: 7.2734
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.1969 - loss: 4.1682 - val_accuracy: 0.1045 - val_loss: 7.3509
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2041 - loss: 4.1016 - val_accuracy: 0.1052 - val_loss: 7.4258
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2138 - loss: 4.0367 - val_accuracy: 0.1032 - val_loss: 7.5291
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2216 - loss: 3.9754 - val_accuracy: 0.1043 - val_loss: 7.5727
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2297 - loss: 3.9163 - val_accuracy: 0.1024 - val_loss: 7.6562
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 110ms/step - accuracy: 0.2375 - loss: 3.8626 - val_accuracy: 0.1020 - val_loss: 7.7481
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2451 - loss: 3.8081 - val_accuracy: 0.1027 - val_loss: 7.8121
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2525 - loss: 3.7565 - val_accuracy: 0.1016 - val_loss: 7.8868
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2604 - loss: 3.7084 - val_accuracy: 0.1017 - val_loss: 7.9480
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2664 - loss: 3.6629 - val_accuracy: 0.1002 - val_loss: 8.0232
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2742 - loss: 3.6175 - val_accuracy: 0.1024 - val_loss: 8.0817
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2788 - loss: 3.5752 - val_accuracy: 0.1004 - val_loss: 8.1416
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.2855 - loss: 3.5324 - val_accuracy: 0.0989 - val_loss: 8.2203
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 108ms/step - accuracy: 0.2905 - loss: 3.4923 - val_accuracy: 0.0990 - val_loss: 8.2599
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.2975 - loss: 3.4509 - val_accuracy: 0.1014 - val_loss: 8.3550
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3025 - loss: 3.4129 - val_accuracy: 0.0991 - val_loss: 8.3847
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3089 - loss: 3.3733 - val_accuracy: 0.0999 - val_loss: 8.4417
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3134 - loss: 3.3391 - val_accuracy: 0.0987 - val_loss: 8.4945
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3188 - loss: 3.3023 - val_accuracy: 0.1011 - val_loss: 8.5692
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 82s 107ms/step - accuracy: 0.3253 - loss: 3.2665 - val_accuracy: 0.0975 - val_loss: 8.6045
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3302 - loss: 3.2337 - val_accuracy: 0.0984 - val_loss: 8.6528
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3352 - loss: 3.1978 - val_accuracy: 0.0992 - val_loss: 8.7044
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3411 - loss: 3.1658 - val_accuracy: 0.0990 - val_loss: 8.7761
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3459 - loss: 3.1376 - val_accuracy: 0.1000 - val_loss: 8.8297
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3496 - loss: 3.1056 - val_accuracy: 0.0989 - val_loss: 8.8610
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3560 - loss: 3.0725 - val_accuracy: 0.0958 - val_loss: 8.9274
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3606 - loss: 3.0424 - val_accuracy: 0.0971 - val_loss: 8.9629
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3672 - loss: 3.0101 - val_accuracy: 0.0978 - val_loss: 9.0169
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3709 - loss: 2.9823 - val_accuracy: 0.0962 - val_loss: 9.0610
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3763 - loss: 2.9562 - val_accuracy: 0.0963 - val_loss: 9.1220
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3819 - loss: 2.9264 - val_accuracy: 0.0946 - val_loss: 9.1650
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3867 - loss: 2.8981 - val_accuracy: 0.0965 - val_loss: 9.2081
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3847 - loss: 2.9038 - val_accuracy: 0.0903 - val_loss: 9.1556
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.3927 - loss: 2.8652 - val_accuracy: 0.0915 - val_loss: 9.2305
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.3969 - loss: 2.8331 - val_accuracy: 0.0939 - val_loss: 9.2779
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4025 - loss: 2.8041 - val_accuracy: 0.0915 - val_loss: 9.3379
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4068 - loss: 2.7784 - val_accuracy: 0.0918 - val_loss: 9.3800
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 110ms/step - accuracy: 0.4110 - loss: 2.7542 - val_accuracy: 0.0942 - val_loss: 9.4302
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4152 - loss: 2.7291 - val_accuracy: 0.0916 - val_loss: 9.4724
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 108ms/step - accuracy: 0.4216 - loss: 2.7011 - val_accuracy: 0.0912 - val_loss: 9.5220
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4246 - loss: 2.6763 - val_accuracy: 0.0891 - val_loss: 9.5733
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4294 - loss: 2.6542 - val_accuracy: 0.0935 - val_loss: 9.6089
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 108ms/step - accuracy: 0.4333 - loss: 2.6284 - val_accuracy: 0.0931 - val_loss: 9.6609
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4363 - loss: 2.6082 - val_accuracy: 0.0910 - val_loss: 9.7266
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 84s 111ms/step - accuracy: 0.4387 - loss: 2.5916 - val_accuracy: 0.0881 - val_loss: 9.7591
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4457 - loss: 2.5597 - val_accuracy: 0.0874 - val_loss: 9.8008
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4502 - loss: 2.5347 - val_accuracy: 0.0915 - val_loss: 9.8450
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4555 - loss: 2.5113 - val_accuracy: 0.0909 - val_loss: 9.9102
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 110ms/step - accuracy: 0.4593 - loss: 2.4889 - val_accuracy: 0.0891 - val_loss: 9.9310
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4616 - loss: 2.4674 - val_accuracy: 0.0874 - val_loss: 9.9696
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4680 - loss: 2.4444 - val_accuracy: 0.0878 - val_loss: 10.0172
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.4706 - loss: 2.4244 - val_accuracy: 0.0890 - val_loss: 10.0605
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 111ms/step - accuracy: 0.4755 - loss: 2.4020 - val_accuracy: 0.0885 - val_loss: 10.1015
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4799 - loss: 2.3799 - val_accuracy: 0.0887 - val_loss: 10.1527
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 108ms/step - accuracy: 0.4810 - loss: 2.3743 - val_accuracy: 0.0848 - val_loss: 10.1939
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 81s 108ms/step - accuracy: 0.4878 - loss: 2.3414 - val_accuracy: 0.0898 - val_loss: 10.2398
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4926 - loss: 2.3189 - val_accuracy: 0.0856 - val_loss: 10.2776
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.4947 - loss: 2.3001 - val_accuracy: 0.0839 - val_loss: 10.3178
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5001 - loss: 2.2786 - val_accuracy: 0.0876 - val_loss: 10.3547
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5038 - loss: 2.2589 - val_accuracy: 0.0851 - val_loss: 10.4111
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 106ms/step - accuracy: 0.5074 - loss: 2.2384 - val_accuracy: 0.0863 - val_loss: 10.4478
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5125 - loss: 2.2181 - val_accuracy: 0.0855 - val_loss: 10.4921
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 109ms/step - accuracy: 0.5155 - loss: 2.1986 - val_accuracy: 0.0814 - val_loss: 10.5372
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5197 - loss: 2.1793 - val_accuracy: 0.0841 - val_loss: 10.5879
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 110ms/step - accuracy: 0.5235 - loss: 2.1616 - val_accuracy: 0.0824 - val_loss: 10.6166
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5277 - loss: 2.1420 - val_accuracy: 0.0842 - val_loss: 10.6662
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5315 - loss: 2.1233 - val_accuracy: 0.0846 - val_loss: 10.7029
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5354 - loss: 2.1038 - val_accuracy: 0.0827 - val_loss: 10.7409
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5385 - loss: 2.0875 - val_accuracy: 0.0817 - val_loss: 10.7876
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5420 - loss: 2.0692 - val_accuracy: 0.0819 - val_loss: 10.8405
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5455 - loss: 2.0524 - val_accuracy: 0.0831 - val_loss: 10.8574
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5511 - loss: 2.0329 - val_accuracy: 0.0849 - val_loss: 10.9212
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5535 - loss: 2.0147 - val_accuracy: 0.0839 - val_loss: 10.9357
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 83s 108ms/step - accuracy: 0.5572 - loss: 1.9986 - val_accuracy: 0.0847 - val_loss: 10.9945
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 66s 111ms/step - accuracy: 0.5605 - loss: 1.9791 - val_accuracy: 0.0807 - val_loss: 11.0366
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5648 - loss: 1.9655 - val_accuracy: 0.0797 - val_loss: 11.0703
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5676 - loss: 1.9481 - val_accuracy: 0.0837 - val_loss: 11.1204
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5702 - loss: 1.9310 - val_accuracy: 0.0810 - val_loss: 11.1543
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 64s 107ms/step - accuracy: 0.5722 - loss: 1.9228 - val_accuracy: 0.0821 - val_loss: 11.1938

In [ ]:
rnn_model_1.save("rnn_model_1.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [ ]:
index_to_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,Tokenizer,text,next_words=1):
  text=text.lower()

  seq=Tokenizer.texts_to_sequences([text])[0]
  for _ in range(next_words):
    seq=pad_sequences([seq],maxlen=max_len,padding='pre')
  pred =model.predict(seq)
  pred_index =np.argmax(pred)
  predicted_word = index_to_word[pred_index]
  return predicted_word ,pred_index

In [ ]:
seed_text ="who"
next_word =predictor(rnn_model_1,tok,seed_text,next_words=1)
print(next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
('are', np.int64(14))

In [ ]:
def generate_text(model, Tokenizer, seed_text, max_len, num_words_to_generate):
   generated_text = seed_text
   for _ in range(num_words_to_generate):
     pred_word, pred_index = predictor(model, Tokenizer, generated_text, next_words=1)
     # Stop if prediction is empty or some other stopping condition if needed
     if pred_word == "":
        break
     generated_text += " " + pred_word
   return generated_text

In [ ]:
seed_text="the meaning of life "
generated_output_text = generate_text(rnn_model_1, tok, seed_text, max_len, num_words_to_generate=10)
print(generated_output_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
the meaning of life  is the purifying fire are winding we do not know

In [ ]:
import pickle
with open ("tokenizer.pkl","wb") as f:
  pickle.dump(tok,f)

In [ ]:

with open ("max_len.pkl","wb") as f:
  pickle.dump(max_len,f)